---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: echo-staging
  namespace: staging
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:staging-*
spec:
  releaseName: echo-staging
  chart:
    git: git@github.com:kobideveleap/gitops
    path: helm-charts/echo
    ref: master
  values:
    image: eu.gcr.io/first-k8s-project-256708/echoapp:1.0.27
    replicaCount: 1
    name: echo-staging
    namespace: staging
    data:
      mongodburl: "mongodb://echo:mypassword@mongodb.default.svc.cluster.local:27017/echo-staging"
