---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: echo-production
  namespace: production
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1.0
spec:
  releaseName: echo-production
  chart:
    git: git@github.com:kobideveleap/gitops
    path: helm-charts/echo
    ref: master
  values:
    image: eu.gcr.io/first-k8s-project-256708/echoapp:1.0.27
    replicaCount: 1
    name: echo-production
    namespace: production
